### PR TITLE
adds template file and updates readme

### PR DESCRIPTION
**Pull request by Frijol**
r? @johnnyman727 or @HipsterBrown

### CODE REVIEW

**Comment by HipsterBrown** [comment]
How should the TWIT be named when someone copies the template?

**Comment by Frijol** [comment]
Good question. By date of publication, in theory, but I think it's an evolving thing at the moment. Do you think we should reorg now that this repo is for all of the blog/not just TWIT?

**Comment by HipsterBrown** [comment]
So for now, how about standardizing on `TWIT-year-month-day.md`? We can add a blog post template and README description in a separate PR. :smile:

**Comment by Frijol** [comment]
makes sense. I swapped around to have TWIT last so that it organizes by date :)

**Comment by Frijol** [comment]
All right, should be clearer now. @HipsterBrown any further review?

**Comment by HipsterBrown** [comment]
LGTM 👍 

Thanks for updating! :smile:

**Pull request merged**
