### PR TITLE
draft

### PR DESCRIPTION
**Pull request by Frijol**
for https://github.com/tessel/this-week-in-tessel/issues/16

### CODE REVIEW

**Comment by Frijol** [comment]
Missing: more current milestones update (cc @rwaldron @johnnyman727)

cc @tcr to look this over too

**Comment by Frijol** [comment]
do I need to mention anything about charging orders? Just waiting on the go-ahead from @johnnyman727 to do this

**Comment by johnnyman727** [comment]
@Frijol the milestones you already have listed here are good. We've also done a ton of bug fixing but I'm not sure if that's interesting. We also have USB BLE and Flash support in a pending PR.

In terms of charging orders, I'd like to review a few things first just to make sure we are 100% ready. Unfortunately, I'll be camping this weekend so the earliest that will happen is Monday.

**Comment by dtex** [comment]
I think y'all are being too humble on the CLI improvements. It is turning into a pretty awesome/powerful tool and blows away everything else I've seen.

**Comment by ferdis** [comment]
Awesome! I like the "How to get more frequent updates" most.

A few things:
- If charging orders, I'd definitely suggest mentioning when it'll happen.
- The 25th Jan date feels a bit opaque IMO. Reading the meeting notes, I would rather say that you expect the boards to begin shipping to customers mid-February (after the holiday). 
- Also with @dtex, very humble about t2-cli("almost there" milestone) and t2-compiler improvements.
- Build server perhaps?

Being able to run binary deps so seamlessly on the tessel is very, very awesome!

Thanks!

**Comment by Frijol** [comment]
Thanks, all! Anything in particular I should call out for CLI improvements? I wasn't sure how to take the bugfixing and turn it into a digestible bullet point.

**Pull request closed without merging**
